# Generated by Django 3.2.7 on 2021-09-20 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('nome', models.CharField(max_length=30)),
                ('dataFundacao', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('quantidade', models.IntegerField()),
                ('ref', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('lojaPertencente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.loja')),
            ],
        ),
    ]
