# Generated by Django 3.2.7 on 2021-09-24 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
