# Generated by Django 3.2.7 on 2021-09-23 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_loja_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loja',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
