# Generated by Django 3.2.7 on 2021-09-25 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_categoria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
