# Generated by Django 3.2.7 on 2021-09-25 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='categoria',
        ),
    ]
