# Generated by Django 3.2.7 on 2021-09-25 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_ref_produto_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='lojaPertencente',
        ),
    ]
