# Generated by Django 3.2.7 on 2021-09-25 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_categoria_lojapertencente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='lojaPertencente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.loja'),
        ),
    ]
