# Generated by Django 3.2.7 on 2021-09-26 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_loja_id'),
        ('app', '0011_alter_categoria_lojapertencente'),
    ]

    operations = [
    ]
